sudo: false
language: node_js
node_js:
- 6.9.1

addons:
  ssh_known_hosts: $knownhost

before_deploy:
- openssl aes-256-cbc -K $encrypted_24af1569a4c2_key -iv $encrypted_24af1569a4c2_iv -in travis_rsa.enc -out travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa
- echo '{"build":"'$TRAVIS_BUILD_NUMBER'"}' > _info.json
- ssh-keyscan -t rsa -H $knownhost >> ~/.ssh/known_hosts 2>&1
- ssh-keyscan -t rsa -H $knownhost_ip >> ~/.ssh/known_hosts 2>&1


deploy:
  - provider: script
    skip_cleanup: true
    script: sh deploy.sh
    on:
      branch: master
